.\" Manpage for zypper-search-packages.
.TH man 8 "18 Apr 2016" "1.0" "zypper-search-packages man page"
.SH NAME
zypper-search-packages \- extended search for packages
.SH SYNOPSIS
zypper search-packages [options] package1 [package2 [...]]
.SH DESCRIPTION
zypper search-packages performs wxtended search for packages covering
all potential SLE modules by querying RMT/SCC.
This operation needs access to a network.

Same as for the normal search operation the search string can be a part of a package
name unless the option --match-exact is used.
.SH OPTIONS
.TP
.B --match-substrings
Search for a match to partial words (default).
.TP
.B -x, --match-exact
Search for an exact match of the search strings
.TP
.B -C, --case-sensitive
Perform case-sensitive search.
.TP
.B --sort-by-name
Sort packages by name (default).
.TP
.B --sort-by-repo
Sort packages by repository or module.
.TP
.B -g, --group-by-module
Group the results by module (default: group by package)
.TP
.B --no-query-local
Do not search installed packages and packages in available repositories.
.TP
.B -s, --details
Display more detailed information about found packages
.TP
.B --xmlout
Switch to XML output
.SH SEE ALSO
zypper(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Jiri Srain <jsrain@suse.com>
